//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtofLivingCentre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testimonial
    {
        public int ReviewId { get; set; }
        public string Subject { get; set; }
        public string Review { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public long Likes { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
